name: Python Tests for Fintech-Backend

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Fintech-Backend/**'
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./Fintech-Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify environment
      working-directory: ./Fintech-Backend
      run: |
        echo "Python in uso: $(where python)"
        pip show Flask
        pip list

    - name: Run tests with pytest
      working-directory: ./Fintech-Backend
      run: |
        py test.py
